---
- name: Deploy Slurm Controller
  hosts: slurm_controller
  become: true
  roles:
    - common/base
    - common/logging
    - slurm/common
    - slurm/controller

- name: Deploy Slurm Worker
  hosts: slurm_worker
  become: true
  roles:
    - common/base
    - common/logging
    - slurm/common
    - slurm/worker
